[build]
  base    = ""
  publish = "app/dist"
  command = "npm run app:build"

# [[redirects]]
#   from = "https://apcry.deadbird.dev/api/*"
#   to = "https://api.apcry.deadbird.dev/cry/:splat"
#   status = 200
#   force = true
